// states
// 0 - havent even gotten past home page
// 1 - at menu
// 2 - created student form
// 3 - sent student form
// 4 - created teacher forms
// 5 - sent teacher forms
// 6 - algorithm run
// 7 - final emails sent

const PROJECTFOLDERIDKEY = "PROJECTFOLDERIDKEY";
const STUDENTFORMIDKEY = "STUDENTFORMIDKEY";
const TEACHERFORMFOLDERIDKEY = "TEACHERFORMFOLDERIDKEY";

const TEACHERPAIRAMOUNT = "TEACHERPAIRAMOUNT";

const HOMESHEETIDKEY = "HOMESHEETIDKEY";
const STUDENTSHEETIDKEY = "STUDENTSHEETIDKEY";
const TEACHERSHEETIDKEY = "TEACHERSHEETIDKEY";

const STUDENTDATASHEETIDKEY = "STUDENTDATASHEETIDKEY";
const TEACHERDATASHEETIDKEY = "TEACHERDATASHEETIDKEY";

const STUDENTMSG = "STUDENTMSG";
const TEACHERMSG = "TEACHERMSG";

const FINALSTUDENTMSG = "FINALSTUDENTMSG";
const FINALTEACHERMSG = "FINALTEACHERMSG";

const STUDENTMSGSSENT = "STUDENTMSGSSENT"
const TEACHERMSGSSENT = "TEACHERMSGSSENT"

const FINALSTUDENTMSGSSENT = "FINALSTUDENTMSGSSENT";
const FINALTEACHERMSGSSENT = "FINALTEACHERMSGSSENT";

const FINALSTUDENTSHEETID = "FINALSTUDENTSHEETID";
const FINALTEACHERSHEETID = "FINALTEACHERSHEETID";

const SURVEYSCREATED = "SURVEYSCREATED"
const SURVEYSSENT = "SURVEYSSENT"
const RESULTSSENT = "RESULTSSENT"

const STUDENTSURVEYID = "STUDENTSURVEYID"
const TEACHERSURVEYID = "TEACHERSURVEYID"

const PROGRAMSTATEKEY = "PROGRAMSTATEKEY"

const LOGSTEPKEY = "LOGSTEPKEY"

const TEACHERFORMSDONE = "TEACHERFORMSDONE"
const STUDENTFORMSDONE = "TEACHERFORMSDONE"
